turrets:
  turret:
    permission: 'turret.shipturret'
    cooldown: 2000
    basematerials:
      - DISPENSER
    topmaterials:
      - GLASS  
    ammo:
      - glowstone
      - redstone
      - gunpowder
    projectile:  Fireball
    velocity: 1.0
      
ammos:
  gunpowder:
    id: SULPHUR
    fire: false
    velocity: 0.50
    quantity: 4
    yield: 2.5
    cooldown: 2500
   